#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
        c=0
        d=0
        for i,e in enumerate(a):
            if a[i]>b[i]:
                c=c+1
                d=d
            elif a[i]<b[i]:
                d=d+1
                c=c
            else:
                c=c
                d=d
        return c,d

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()

