#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    max1=0
    min1=0
    max1= sum(arr)-min(arr)
    min1= sum(arr)-max(arr)
    print(min1, max1)

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)

