#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the palindromeIndex function below.
def palindromeIndex(s):
    for i in range(math.ceil(len(s)/2)):
        if s[i] == s[len(s)-i-1]:
            continue
        else:
            k = i
            if s[i+1] == s[len(s)-i-1] and s[i+2] == s[len(s)-i-2]:
                return k
            else:
                return len(s)-i-1
    return -1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = palindromeIndex(s)

        fptr.write(str(result) + '\n')

    fptr.close()

