#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    positive=0
    negative=0
    neutral=0
    for i in arr:
        if i>0:
            positive=positive+1    
        elif i<0:
            negative=negative+1
        elif i==0:
            neutral=neutral+1
    ar=[positive/len(arr),negative/len(arr),neutral/len(arr)]
    print(*ar, sep = "\n") 


if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)

